#!/usr/bin/env python3
"""
Solar schedule generator for Every Camera.

Calculates sunrise/sunset times for a given solar altitude angle
and generates a schedule file compatible with Canon and Infra cameras.

Usage:
    # Console mode (interactive)
    python schedule_generator.py

    # Console mode with arguments
    python schedule_generator.py --lat 51.8106 --lon 103.0755 --alt 680 \
        --angle -10 --start 2026-01-01 --days 100 --output schedule.txt

    # GUI mode
    python schedule_generator.py --gui
"""
import argparse
import sys
import os
from datetime import datetime, timedelta

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# Predefined observation sites
# ---------------------------------------------------------------------------
SITES = {
    "GPHO_TK": {"name": "GPHO Tory", "lat": 51 + 48/60 + 38.09/3600, "lon": 103 + 4/60 + 31.67/3600, "alt": 680},
    "KLNG_1": {"name": "Kaliningrad", "lat": 54.60333, "lon": 20.21109, "alt": 30},
    "MAGNITKA": {"name": "Magnitka", "lat": 55.930547, "lon": 48.744878, "alt": 95},
    "SURA_ISZF": {"name": "SURA ISZF", "lat": 56.147122, "lon": 46.098528, "alt": 172},
    "SURA_NNGU": {"name": "SURA NNGU", "lat": 56.150172, "lon": 46.105006, "alt": 184},
    "SURA": {"name": "SURA", "lat": 56 + 8/60 + 37.2/3600, "lon": 46 + 5/60 + 56.57/3600, "alt": 173},
    "PEREVOZ": {"name": "Perevoz", "lat": 55.542581, "lon": 44.535734, "alt": 155},
}


# ---------------------------------------------------------------------------
# Core computation
# ---------------------------------------------------------------------------
def compute_sun_on_off(date, location, angle):
    """
    Find the times when the sun crosses a given altitude angle.

    Parameters:
        date: datetime (start of day, UTC)
        location: astropy EarthLocation
        angle: float, altitude angle in degrees

    Returns:
        (sunrise_time, sunset_time) as datetime objects or (None, None)
        if the sun never reaches the angle on this day.
    """
    from astropy.coordinates import get_sun, AltAz
    from astropy.time import Time

    prev_alt = None
    sunrise_time = None
    sunset_time = None

    for h in range(24):
        for m in range(60):
            t = date + timedelta(hours=h, minutes=m)
            astro_time = Time(t, scale='utc')
            altaz = AltAz(obstime=astro_time, location=location)
            sun_alt = get_sun(astro_time).transform_to(altaz).alt.degree

            if prev_alt is not None:
                rising = sun_alt > prev_alt
                if rising and sunrise_time is None and sun_alt > angle and sun_alt < angle + 1:
                    sunrise_time = t
                if not rising and sunset_time is None and sun_alt < angle:
                    sunset_time = t

            prev_alt = sun_alt

    return sunrise_time, sunset_time


def generate_schedule(lat, lon, alt_m, angle, start_date, num_days,
                      progress_cb=None):
    """
    Generate schedule entries for a range of dates.

    Returns list of (date_str, sunrise_utc, sunset_utc) tuples.
    Entries where the sun never reaches the angle are skipped.
    """
    from astropy.coordinates import EarthLocation
    from astropy import units as u

    location = EarthLocation(lon=lon * u.degree, lat=lat * u.degree,
                             height=alt_m * u.meter)

    results = []
    for day_idx in range(num_days):
        current_date = start_date + timedelta(days=day_idx)
        sunrise, sunset = compute_sun_on_off(current_date, location, angle)

        if sunrise and sunset:
            results.append({
                "date": current_date.strftime("%d.%m.%Y"),
                "start": sunrise,
                "end": sunset,
            })

        if progress_cb:
            progress_cb(day_idx + 1, num_days)

    return results


def write_schedule_file(filepath, entries):
    """Write schedule entries to a file in Every Camera format."""
    from utils import SCHEDULE_DT_FMT
    with open(filepath, "w") as f:
        f.write("# Measurement Schedule (generated by schedule_generator.py)\n")
        f.write(f"# Format: {SCHEDULE_DT_FMT} - {SCHEDULE_DT_FMT}\n")
        f.write(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        for e in entries:
            start_str = e["start"].strftime(SCHEDULE_DT_FMT)
            end_str = e["end"].strftime(SCHEDULE_DT_FMT)
            f.write(f"{start_str} - {end_str}\n")


# ---------------------------------------------------------------------------
# Console mode
# ---------------------------------------------------------------------------
def run_console(args):
    """Interactive or argument-based console schedule generation."""
    lat = args.lat
    lon = args.lon
    alt_m = args.alt
    angle = args.angle
    start = args.start
    days = args.days
    output = args.output

    # Interactive mode if required params missing
    if lat is None or lon is None:
        print("=" * 60)
        print("  Solar Schedule Generator")
        print("=" * 60)
        print("\nPredefined sites:")
        for i, (key, site) in enumerate(SITES.items(), 1):
            print(f"  {i}. {site['name']} ({key}): "
                  f"lat={site['lat']:.4f}, lon={site['lon']:.4f}, alt={site['alt']}m")
        print(f"  0. Custom coordinates")

        try:
            choice = int(input("\nSelect site [0]: ").strip() or "0")
        except ValueError:
            choice = 0

        if 1 <= choice <= len(SITES):
            site_key = list(SITES.keys())[choice - 1]
            site = SITES[site_key]
            lat = site["lat"]
            lon = site["lon"]
            alt_m = site["alt"]
            print(f"\nSelected: {site['name']}")
        else:
            lat = float(input("Latitude (degrees): ").strip())
            lon = float(input("Longitude (degrees): ").strip())
            alt_m = float(input("Altitude (meters) [0]: ").strip() or "0")

    if angle is None:
        angle = float(input("Sun altitude angle (degrees, e.g. -10): ").strip() or "-10")

    if start is None:
        start_str = input(f"Start date (YYYY-MM-DD) [{datetime.now().strftime('%Y-%m-%d')}]: ").strip()
        start = datetime.strptime(start_str, "%Y-%m-%d") if start_str else datetime.now().replace(
            hour=0, minute=0, second=0, microsecond=0)

    if days is None:
        days = int(input("Number of days [100]: ").strip() or "100")

    if output is None:
        output = input("Output file [schedule.txt]: ").strip() or "schedule.txt"

    print(f"\nParameters:")
    print(f"  Location  : lat={lat:.4f}, lon={lon:.4f}, alt={alt_m}m")
    print(f"  Angle     : {angle} degrees")
    print(f"  Period    : {start.strftime('%Y-%m-%d')} + {days} days")
    print(f"  Output    : {output}")
    print()

    def progress(current, total):
        pct = current * 100 // total
        bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
        print(f"\r  [{bar}] {current}/{total} days", end="", flush=True)

    print("Computing solar angles...")
    results = generate_schedule(lat, lon, alt_m, angle, start, days,
                                progress_cb=progress)
    print()

    if not results:
        print("No schedule entries generated (sun never reaches the specified angle).")
        return

    write_schedule_file(output, results)
    print(f"\nGenerated {len(results)} schedule entries -> {output}")
    print("\nPreview (first 10 entries):")
    for e in results[:10]:
        print(f"  {e['date']}  {e['start'].strftime('%H:%M')} - {e['end'].strftime('%H:%M')} UTC")
    if len(results) > 10:
        print(f"  ... and {len(results) - 10} more")


# ---------------------------------------------------------------------------
# GUI mode
# ---------------------------------------------------------------------------
def run_gui():
    """PyQt5 GUI for schedule generation."""
    from PyQt5.QtWidgets import (
        QApplication, QWidget, QVBoxLayout, QHBoxLayout, QGridLayout,
        QLabel, QLineEdit, QSpinBox, QDoubleSpinBox, QPushButton,
        QComboBox, QTextEdit, QFileDialog, QGroupBox, QProgressBar,
        QDateEdit, QMessageBox,
    )
    from PyQt5.QtCore import Qt, QThread, pyqtSignal, QDate

    class GeneratorThread(QThread):
        progress = pyqtSignal(int, int)
        finished_ok = pyqtSignal(list)
        error = pyqtSignal(str)

        def __init__(self, lat, lon, alt_m, angle, start_date, num_days):
            super().__init__()
            self.lat = lat
            self.lon = lon
            self.alt_m = alt_m
            self.angle = angle
            self.start_date = start_date
            self.num_days = num_days

        def run(self):
            try:
                results = generate_schedule(
                    self.lat, self.lon, self.alt_m,
                    self.angle, self.start_date, self.num_days,
                    progress_cb=lambda c, t: self.progress.emit(c, t),
                )
                self.finished_ok.emit(results)
            except Exception as e:
                self.error.emit(str(e))

    class ScheduleGeneratorWindow(QWidget):
        def __init__(self):
            super().__init__()
            self.setWindowTitle("Solar Schedule Generator")
            self.setMinimumSize(600, 500)
            self._thread = None
            self._results = []
            self._build_ui()

        def _build_ui(self):
            layout = QVBoxLayout(self)

            # Site selection
            grp_site = QGroupBox("Observation Site")
            site_lay = QGridLayout(grp_site)

            site_lay.addWidget(QLabel("Preset:"), 0, 0)
            self.combo_site = QComboBox()
            self.combo_site.addItem("Custom", None)
            for key, site in SITES.items():
                self.combo_site.addItem(f"{site['name']} ({key})", key)
            self.combo_site.currentIndexChanged.connect(self._on_site_changed)
            site_lay.addWidget(self.combo_site, 0, 1, 1, 3)

            site_lay.addWidget(QLabel("Latitude:"), 1, 0)
            self.sp_lat = QDoubleSpinBox()
            self.sp_lat.setRange(-90, 90)
            self.sp_lat.setDecimals(6)
            self.sp_lat.setSuffix(" °")
            site_lay.addWidget(self.sp_lat, 1, 1)

            site_lay.addWidget(QLabel("Longitude:"), 1, 2)
            self.sp_lon = QDoubleSpinBox()
            self.sp_lon.setRange(-180, 180)
            self.sp_lon.setDecimals(6)
            self.sp_lon.setSuffix(" °")
            site_lay.addWidget(self.sp_lon, 1, 3)

            site_lay.addWidget(QLabel("Altitude:"), 2, 0)
            self.sp_alt = QDoubleSpinBox()
            self.sp_alt.setRange(0, 10000)
            self.sp_alt.setDecimals(0)
            self.sp_alt.setSuffix(" m")
            site_lay.addWidget(self.sp_alt, 2, 1)

            layout.addWidget(grp_site)

            # Parameters
            grp_params = QGroupBox("Parameters")
            params_lay = QGridLayout(grp_params)

            params_lay.addWidget(QLabel("Sun angle:"), 0, 0)
            self.sp_angle = QDoubleSpinBox()
            self.sp_angle.setRange(-90, 90)
            self.sp_angle.setDecimals(1)
            self.sp_angle.setValue(-10)
            self.sp_angle.setSuffix(" °")
            params_lay.addWidget(self.sp_angle, 0, 1)

            params_lay.addWidget(QLabel("Start date:"), 1, 0)
            self.de_start = QDateEdit()
            self.de_start.setCalendarPopup(True)
            self.de_start.setDate(QDate.currentDate())
            params_lay.addWidget(self.de_start, 1, 1)

            params_lay.addWidget(QLabel("Days:"), 2, 0)
            self.sp_days = QSpinBox()
            self.sp_days.setRange(1, 3650)
            self.sp_days.setValue(100)
            params_lay.addWidget(self.sp_days, 2, 1)

            layout.addWidget(grp_params)

            # Actions
            btn_lay = QHBoxLayout()
            self.btn_generate = QPushButton("Generate")
            self.btn_generate.setStyleSheet(
                "background:#2a7a2a; color:white; font-weight:bold; padding:6px 18px;")
            self.btn_generate.clicked.connect(self._on_generate)
            btn_lay.addWidget(self.btn_generate)

            self.btn_save = QPushButton("Save to file...")
            self.btn_save.setEnabled(False)
            self.btn_save.clicked.connect(self._on_save)
            btn_lay.addWidget(self.btn_save)
            layout.addLayout(btn_lay)

            # Progress
            self.progress_bar = QProgressBar()
            self.progress_bar.setVisible(False)
            layout.addWidget(self.progress_bar)

            # Results
            self.txt_results = QTextEdit()
            self.txt_results.setReadOnly(True)
            self.txt_results.setStyleSheet("font-family: monospace;")
            layout.addWidget(self.txt_results)

        def _on_site_changed(self, idx):
            key = self.combo_site.currentData()
            if key and key in SITES:
                site = SITES[key]
                self.sp_lat.setValue(site["lat"])
                self.sp_lon.setValue(site["lon"])
                self.sp_alt.setValue(site["alt"])

        def _on_generate(self):
            if self._thread and self._thread.isRunning():
                return

            lat = self.sp_lat.value()
            lon = self.sp_lon.value()
            alt_m = self.sp_alt.value()
            angle = self.sp_angle.value()
            qdate = self.de_start.date()
            start_date = datetime(qdate.year(), qdate.month(), qdate.day())
            num_days = self.sp_days.value()

            self.txt_results.clear()
            self.txt_results.append(
                f"Computing: lat={lat:.4f}, lon={lon:.4f}, alt={alt_m:.0f}m\n"
                f"Angle: {angle}°, Start: {start_date.strftime('%Y-%m-%d')}, "
                f"Days: {num_days}\n"
            )
            self.progress_bar.setVisible(True)
            self.progress_bar.setRange(0, num_days)
            self.progress_bar.setValue(0)
            self.btn_generate.setEnabled(False)

            self._thread = GeneratorThread(lat, lon, alt_m, angle, start_date, num_days)
            self._thread.progress.connect(self._on_progress)
            self._thread.finished_ok.connect(self._on_finished)
            self._thread.error.connect(self._on_error)
            self._thread.start()

        def _on_progress(self, current, total):
            self.progress_bar.setValue(current)

        def _on_finished(self, results):
            self._results = results
            self.progress_bar.setVisible(False)
            self.btn_generate.setEnabled(True)
            self.btn_save.setEnabled(bool(results))

            if not results:
                self.txt_results.append(
                    "\nNo entries: sun never reaches the specified angle.")
                return

            self.txt_results.append(f"\nGenerated {len(results)} entries:\n")
            self.txt_results.append(f"{'Date':<12} {'Start (UTC)':<14} {'End (UTC)'}")
            self.txt_results.append("-" * 40)
            for e in results:
                self.txt_results.append(
                    f"{e['date']:<12} {e['start'].strftime('%H:%M'):<14} "
                    f"{e['end'].strftime('%H:%M')}"
                )

        def _on_error(self, msg):
            self.progress_bar.setVisible(False)
            self.btn_generate.setEnabled(True)
            QMessageBox.critical(self, "Error", msg)

        def _on_save(self):
            if not self._results:
                return
            path, _ = QFileDialog.getSaveFileName(
                self, "Save schedule", "schedule.txt",
                "Text files (*.txt);;All (*)")
            if not path:
                return
            write_schedule_file(path, self._results)
            self.txt_results.append(f"\nSaved to: {path}")

    app = QApplication(sys.argv)
    win = ScheduleGeneratorWindow()
    win.show()
    sys.exit(app.exec_())


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Solar Schedule Generator for Every Camera",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Predefined sites: """ + ", ".join(SITES.keys()) + """

Examples:
  python schedule_generator.py --gui
  python schedule_generator.py --lat 51.81 --lon 103.08 --alt 680 --angle -10 --start 2026-01-01 --days 100
  python schedule_generator.py   # interactive console mode
        """,
    )
    parser.add_argument("--gui", action="store_true",
                        help="Launch GUI mode")
    parser.add_argument("--lat", type=float, default=None,
                        help="Latitude (degrees)")
    parser.add_argument("--lon", type=float, default=None,
                        help="Longitude (degrees)")
    parser.add_argument("--alt", type=float, default=0,
                        help="Altitude above sea level (meters)")
    parser.add_argument("--angle", type=float, default=None,
                        help="Sun altitude angle threshold (degrees, e.g. -10)")
    parser.add_argument("--start", type=lambda s: datetime.strptime(s, "%Y-%m-%d"),
                        default=None, help="Start date (YYYY-MM-DD)")
    parser.add_argument("--days", type=int, default=None,
                        help="Number of days to compute")
    parser.add_argument("--output", "-o", type=str, default=None,
                        help="Output schedule file path")
    parser.add_argument("--site", type=str, default=None,
                        choices=list(SITES.keys()),
                        help="Use predefined site coordinates")

    args = parser.parse_args()

    # Apply site preset
    if args.site and args.site in SITES:
        site = SITES[args.site]
        if args.lat is None:
            args.lat = site["lat"]
        if args.lon is None:
            args.lon = site["lon"]
        if args.alt == 0:
            args.alt = site["alt"]

    if args.gui:
        run_gui()
    else:
        run_console(args)


if __name__ == "__main__":
    main()
