"""The exact ASI FITS header, card for card, in order.

``tests/test_asi_archive.py`` already checks that each individual name survives a
round trip. This file checks something the per-name assertions cannot: that the
*whole* header is what it is today — every card, its value, its comment, and the
order they appear in. astropy serialises a header in card order, so pinning the
order pins the bytes.

That matters because the station's processing program was written against
imagerd_rt's output and reads these names positionally in places. It matters more
because the writer is about to be rebuilt on top of a shared core
(``cameras/common/fits.py``) so the Hamamatsu camera can use the same eighteen
core cards: a refactor whose whole promise is "the output does not change" needs
one test that would notice if it did.

The two cases are the two shapes the writer actually produces: a cycle-mode frame
that supplies every optional argument, and a sun-mode frame that supplies none of
them. Between them every conditional branch in ``write_fits`` is covered.

The expected lists were generated by running the writer, not written by hand. To
regenerate them after a *deliberate* header change, run this module as a script:

    python tests/test_asi_fits_header.py
"""
import sys
import warnings

from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from cameras.asi.fits import write_fits                # noqa: E402

fits = pytest.importorskip("astropy.io.fits")

# Aware, so the expected strings do not depend on the machine's time zone.
NOON_UTC = datetime(2026, 7, 28, 12, 0, 0, tzinfo=timezone.utc)

# Written by astropy itself, before and after the header we build. They are
# listed so the comparison covers the complete card sequence rather than a slice
# somebody could quietly widen.
STRUCTURAL_HEAD = [
    ("SIMPLE", True, "conforms to FITS standard"),
    ("BITPIX", 16, "array data type"),
    ("NAXIS", 2, "number of array dimensions"),
    ("NAXIS1", 4, ""),
    ("NAXIS2", 4, ""),
]
STRUCTURAL_TAIL = [
    ("BSCALE", 1, ""),
    ("BZERO", 32768, ""),
]

# A cycle-mode frame from a station that fills in everything.
FULL_KWARGS = dict(
    timestamp=NOON_UTC, exposure_sec=55.0, binning=4, readout_speed=2.0,
    filter_num=1, ccd_temp=-60.123, image_type="LIGHT", obs_mode="sun_cycle",
    camera_vendor="Princeton Instruments", camera_model="Pixis2048B",
    camera_sn="SN1", camera_version="fw", driver_version="drv",
    dcam_version="picam", lat=51.810646, lon=103.075555, elevation=658.0,
    gain=3, set_temp=-60.0, bit_depth=16, seqno=42, site_id="TORY",
    device_id="ASI0", filter_wavelength="5577",
    filter_description="557.7nm x 2.0nm", fw_temp=23.456,
    sky_mean=12345.678, split_count=3, split_index=2,
)

# The same frame with every optional argument left out: no cooling setpoint, no
# gain, no bit depth, no SEQNO, no intensity, one frame in the slot.
MINIMAL_KWARGS = dict(
    timestamp=NOON_UTC, exposure_sec=55.0, binning=4, readout_speed=2.0,
    filter_num=1, ccd_temp=None, image_type="LIGHT", obs_mode="sun",
    camera_vendor="Princeton Instruments", camera_model="Pixis2048B",
    camera_sn="SN1", camera_version="fw", driver_version="drv",
    dcam_version="picam", lat=51.810646, lon=103.075555, elevation=658.0,
)

FULL_CARDS = STRUCTURAL_HEAD + [
    # ── the eighteen core cards, shared with the Hamamatsu writer ──────────
    ("DATE-OBS", "2026-07-28T12:00:00.000", "UTC observation start time"),
    ("DATE-LOC", "2026-07-28T12:00:00.000", "local observation start time"),
    ("EXPTIME", 55.0, "[s] exposure duration"),
    # The legacy ``Binning`` write lands on this same card — same value, same
    # meaning — so it appears once, here, with the modern comment.
    ("BINNING", 4, "pixel binning NxN"),
    ("READSPD", 2.0, "[MHz] ADC readout speed"),
    ("FILTER", 1, "filter wheel position"),
    ("CCD-TEMP", -60.123, "[C] CCD sensor temperature"),
    ("IMAGETYP", "LIGHT", "frame type: LIGHT or DARK"),
    ("OBSMODE", "sun_cycle", "observation mode; see also SPLITNUM"),
    ("INSTRUME", "Pixis2048B", "camera model"),
    ("VENDOR", "Princeton Instruments", "camera manufacturer"),
    ("CAMSN", "SN1", "camera serial number"),
    ("CAMVER", "fw", "camera firmware version"),
    ("DRVVER", "drv", "camera driver version"),
    ("DCAMVER", "picam", "camera SDK (PICAM) version"),
    ("SITELAT", 51.810646, "[deg] observatory latitude"),
    ("SITELON", 103.075555, "[deg] observatory longitude"),
    ("SITEELEV", 658.0, "[m] observatory elevation"),
    # ── PIXIS-only, and what the intensity loops decided ──────────────────
    ("GAIN", 3, "ADC analog gain: 1 Low, 2 Medium, 3 High"),
    ("SETTEMP", -60.0, "[C] sensor temperature setpoint"),
    ("SKYMEAN", 12345.68, "[ADU] mean frame intensity"),
    ("SPLITNUM", 3, "sub-frames this slot was divided into"),
    ("SPLITIDX", 2, "index of this sub-frame, 1-based"),
    # ── imagerd_rt's own metadata, in imagerd_rt's order ──────────────────
    ("BITDEPTH", 16, "sensor bit depth"),
    ("CCDGAIN", 3, "ADC analog gain: 1 Low, 2 Medium, 3 High"),
    ("CCDTEMP", -60.12, "[C] CCD sensor temperature"),
    ("EXPOSURE", "55000.00 ms", "exposure duration"),
    ("ReadoutSpeed", "2 MHz", "ADC readout speed"),
    ("SEQNO", 42, "archive frame sequence number"),
    ("SITEID", "TORY", "station identifier"),
    ("DEVICEID", "ASI0", "imager identifier"),
    ("LATITUDE", 51.81, "[deg] observatory latitude"),
    ("Longitude", 103.08, "[deg] observatory longitude"),
    ("FilterWavelength", "5577", "filter wavelength tag"),
    ("FilterPosition", 1, "filter wheel position"),
    ("FilterDescription", "557.7nm x 2.0nm", "filter description"),
    ("FWTEMP", 23.46, "[C] filter wheel temperature"),
    ("VERSION", "3.0", "imagerd_rt metadata version"),
] + STRUCTURAL_TAIL

MINIMAL_CARDS = STRUCTURAL_HEAD + [
    ("DATE-OBS", "2026-07-28T12:00:00.000", "UTC observation start time"),
    ("DATE-LOC", "2026-07-28T12:00:00.000", "local observation start time"),
    ("EXPTIME", 55.0, "[s] exposure duration"),
    ("BINNING", 4, "pixel binning NxN"),
    ("READSPD", 2.0, "[MHz] ADC readout speed"),
    ("FILTER", 1, "filter wheel position"),
    # No reading available, so the value imagerd_rt used for "unknown".
    ("CCD-TEMP", -999.0, "[C] CCD sensor temperature"),
    ("IMAGETYP", "LIGHT", "frame type: LIGHT or DARK"),
    ("OBSMODE", "sun", "observation mode; see also SPLITNUM"),
    ("INSTRUME", "Pixis2048B", "camera model"),
    ("VENDOR", "Princeton Instruments", "camera manufacturer"),
    ("CAMSN", "SN1", "camera serial number"),
    ("CAMVER", "fw", "camera firmware version"),
    ("DRVVER", "drv", "camera driver version"),
    ("DCAMVER", "picam", "camera SDK (PICAM) version"),
    ("SITELAT", 51.810646, "[deg] observatory latitude"),
    ("SITELON", 103.075555, "[deg] observatory longitude"),
    ("SITEELEV", 658.0, "[m] observatory elevation"),
    # GAIN, SETTEMP, SKYMEAN, SPLITNUM, SPLITIDX, BITDEPTH, CCDGAIN and SEQNO
    # are all absent — each is written only when its value was supplied.
    ("CCDTEMP", -999.0, "[C] CCD sensor temperature"),
    ("EXPOSURE", "55000.00 ms", "exposure duration"),
    ("ReadoutSpeed", "2 MHz", "ADC readout speed"),
    ("SITEID", "", "station identifier"),
    ("DEVICEID", "", "imager identifier"),
    ("LATITUDE", 51.81, "[deg] observatory latitude"),
    ("Longitude", 103.08, "[deg] observatory longitude"),
    ("FilterWavelength", "", "filter wavelength tag"),
    ("FilterPosition", 1, "filter wheel position"),
    ("FilterDescription", "", "filter description"),
    ("FWTEMP", -999.0, "[C] filter wheel temperature"),
    ("VERSION", "3.0", "imagerd_rt metadata version"),
] + STRUCTURAL_TAIL


def cards_of(path, **kwargs):
    """Write one frame and return its header as ``[(keyword, value, comment)]``."""
    # The long legacy names become HIERARCH cards on purpose; the writer already
    # silences that warning, and nothing here should turn it back into noise.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        write_fits(path, np.zeros((4, 4), dtype="<u2"), **kwargs)
    header = fits.getheader(path)
    return [(card.keyword, card.value, card.comment) for card in header.cards]


def assert_cards_match(actual, expected):
    """Compare card by card, so a failure names the card that moved."""
    assert [name for name, _, _ in actual] == [name for name, _, _ in expected]
    for (name, value, comment), (_, want_value, want_comment) in zip(actual,
                                                                    expected):
        if isinstance(want_value, float):
            assert value == pytest.approx(want_value), name
        else:
            assert value == want_value, name
        assert comment == want_comment, name


def test_a_full_frames_header_is_card_for_card_what_it_has_always_been(tmp_path):
    assert_cards_match(cards_of(tmp_path / "full.fits", **FULL_KWARGS),
                       FULL_CARDS)


def test_a_frame_with_no_optional_values_omits_exactly_those_cards(tmp_path):
    assert_cards_match(cards_of(tmp_path / "minimal.fits", **MINIMAL_KWARGS),
                       MINIMAL_CARDS)


def test_the_optional_cards_are_the_only_difference_between_the_two(tmp_path):
    """Spelled out, so a card moving *between* the blocks cannot pass unnoticed."""
    full = [name for name, _, _ in cards_of(tmp_path / "a.fits", **FULL_KWARGS)]
    minimal = [name for name, _, _ in cards_of(tmp_path / "b.fits",
                                               **MINIMAL_KWARGS)]
    assert [name for name in full if name not in minimal] == [
        "GAIN", "SETTEMP", "SKYMEAN", "SPLITNUM", "SPLITIDX",
        "BITDEPTH", "CCDGAIN", "SEQNO",
    ]
    assert [name for name in minimal if name not in full] == []


def test_a_split_of_one_writes_no_split_cards(tmp_path):
    """The pair appears only when a slot was actually divided."""
    names = [name for name, _, _ in cards_of(
        tmp_path / "one.fits", **dict(FULL_KWARGS, split_count=1, split_index=1))]
    assert "SPLITNUM" not in names and "SPLITIDX" not in names


def test_writing_refuses_to_overwrite_an_existing_frame(tmp_path):
    path = tmp_path / "frame.fits"
    cards_of(path, **FULL_KWARGS)
    with pytest.raises(OSError):
        cards_of(path, **FULL_KWARGS)


def test_a_failed_capture_is_refused_rather_than_filed_as_an_empty_frame(tmp_path):
    with pytest.raises(ValueError, match="image data is None"):
        write_fits(tmp_path / "none.fits", None, **FULL_KWARGS)


if __name__ == "__main__":  # pragma: no cover - regeneration helper
    import tempfile

    for label, kwargs in (("FULL_CARDS", FULL_KWARGS),
                          ("MINIMAL_CARDS", MINIMAL_KWARGS)):
        with tempfile.TemporaryDirectory() as directory:
            print(f"{label} = [")
            for card in cards_of(Path(directory) / "f.fits", **kwargs):
                print(f"    {card!r},")
            print("]\n")
