"""
Sentry camera driver: Princeton Instruments CCD via imagerd_rt daemon.

The sentry camera is controlled by the pre-compiled `imagerd_rt` binary
(Keo Scientific / Princeton Instruments PicamSDK + Pleora eBUS SDK).
This driver acts as a supervisor: it generates the schedule.conf, starts
the daemon, monitors its outputs, and publishes status/frames via MQTT.

Interface with imagerd_rt:
  Input:   <imagerd_rt_dir>/schedule.conf   — imaging schedule
  Output:  <imagerd_rt_dir>/aux/meta-data.txt  — current frame metadata
           <imagerd_rt_dir>/aux/image.fits      — latest captured frame
           <imagerd_rt_dir>/aux/seqno.txt       — sequence counter
  Control: <imagerd_rt_dir>/aux/stop_file      — write "10" to stop,
                                                  write "11" to resume

Config in config.json (human-readable, replaces raw schedule.conf):
  sentry.imagerd_rt_dir  — installation directory (default /usr/local/imagerd_rt)
  sentry.output_dir      — where FITS images are archived
  sentry.device_id       — camera device ID (e.g. "ASI1")
  sentry.site_id         — station identifier
  sentry.zenith_angle_start — solar zenith angle to begin night (default -10)
  sentry.schedule_len_ms — duration of one imaging cycle in ms (default 1440000)
  sentry.slots           — list of imaging slots (see DEFAULT_CONFIG in utils.py)
"""
import os
import sys
import json
import shutil
import subprocess
import threading
import time

import console_ui

import numpy as np

from datetime import datetime as dt
from pathlib import Path

import frame_archive

from utils import (
    claim_instance_name, get_instance_name, get_local_ip,
    get_system_info, APP_DIR,
)
from worker_common import (
    WorkerMqtt, announce_setup_mode, SETUP_STATUS,
    install_stop_handler, stop_signal_name,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SENTRY_CAPTURE_SECONDS = [0, 30]

_SCHEDULE_CONF_HEADER = """\
#******************************************************************************#
#                      SCHEDULE INITIALIZATION PROGRAM                         #
#******************************************************************************#
#                            Keo Scientific LTD.                               #
#                               Version: 3.0                                   #
#******************************************************************************#

#Schedule Configuration File — generated by every-camera

"""


# ---------------------------------------------------------------------------
# Schedule.conf generation
# ---------------------------------------------------------------------------
def generate_schedule_conf(cfg: dict) -> str:
    """Generate imagerd_rt schedule.conf text from every-camera sentry config.

    Args:
        cfg: the ``sentry`` sub-dict from config.json.

    Returns:
        String content ready to write to schedule.conf.
    """
    device_id = cfg.get("device_id", "ASI1")
    # imaging_mode: "schedule" (0) or "rapid" (1) — also accepts legacy int 0/1
    mode_val = cfg.get("imaging_mode", cfg.get("image_mode", "schedule"))
    if isinstance(mode_val, int):
        image_mode = mode_val
    else:
        image_mode = 0 if str(mode_val).lower() == "schedule" else 1
    zenith = cfg.get("zenith_angle_start", -10)
    sched_len = cfg.get("schedule_len_ms", 1440000)
    slots = cfg.get("slots", [])

    lines = [
        _SCHEDULE_CONF_HEADER,
        f"device ID = {device_id}",
        "",
        "#0 = schedule; 1 = rapid",
        f"image_mode={image_mode}",
        "",
        "#Starting Sun Angle",
        f"zenith_angle_start={zenith}",
        "",
        "#Length of schedule",
        f"schedule_len={sched_len}",
    ]

    for slot in slots:
        filter_num = slot.get("filter_num", 1)
        # start_ms is the new name; start_time_ms kept for backward compat
        start_time = slot.get("start_ms", slot.get("start_time_ms", 0))
        exposure_len = slot.get("exposure_ms", 55000)
        binning = slot.get("binning", 2)
        # gain is the new name; ccd_gain kept for backward compat
        ccd_gain = slot.get("gain", slot.get("ccd_gain", 3))
        # readout_ms is the new name; prep_time_ms kept for backward compat
        prep_time = slot.get("readout_ms", slot.get("prep_time_ms", 5000))

        lines += [
            "#slot values",
            "<slot>",
            "",
            "#Filter number for this slot",
            f"filter_num={filter_num}",
            "#Slot start time",
            f"start_time={start_time}",
            "#Exposure time for this schedule slot",
            f"exposure_len={exposure_len}",
            "#binning value for this schedule slot",
            f"binning={binning}",
            "#CCD gain for this schedule slot",
            f"ccd_gain={ccd_gain}",
            "",
            "",
            "#ms it takes to move filter wheel and readout image",
            "<prep>",
            f"prep_time={prep_time}",
            "</prep>",
            "",
            "</slot>",
        ]

    return "\n".join(lines) + "\n"


def parse_metadata(text: str) -> dict:
    """Parse imagerd_rt aux/meta-data.txt (tab-separated key-value pairs)."""
    meta = {}
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if "\t" in line:
            key, _, val = line.partition("\t")
        elif " " in line:
            # fallback for space-separated
            key, _, val = line.partition(" ")
        else:
            continue
        meta[key.strip()] = val.strip()
    return meta


# ---------------------------------------------------------------------------
# SentryCamera — low-level wrapper around imagerd_rt
# ---------------------------------------------------------------------------
class SentryCamera:
    """Supervisor wrapper for the imagerd_rt daemon.

    Does NOT communicate with the CCD hardware directly; instead it manages
    the imagerd_rt process, reads its output files, and writes schedule.conf.
    """

    def __init__(self, imagerd_rt_dir: str = "/usr/local/imagerd_rt"):
        self._dir = Path(imagerd_rt_dir)
        self._aux_dir = self._dir / "aux"
        self._start_bin = self._dir / "imagerd_rt_start"
        self._stop_bin = self._dir / "imagerd_rt_stop"
        self._stop_file = self._aux_dir / "stop_file"
        self._seqno_file = self._aux_dir / "seqno.txt"
        self._meta_file = self._aux_dir / "meta-data.txt"
        self._image_file = self._aux_dir / "image.fits"
        self._schedule_conf = self._dir / "schedule.conf"

    # ------------------------------------------------------------------
    # Availability checks
    # ------------------------------------------------------------------
    def is_available(self) -> bool:
        """Return True if the imagerd_rt installation is present."""
        return self._start_bin.exists() and self._aux_dir.is_dir()

    def is_running(self) -> bool:
        """Return True if an imagerd_rt process is alive."""
        try:
            result = subprocess.run(
                ["pgrep", "-f", "imagerd_rt"],
                capture_output=True, timeout=3,
            )
            return result.returncode == 0
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def start(self):
        """Launch imagerd_rt_start as a detached background process."""
        if not self._start_bin.exists():
            raise FileNotFoundError(
                f"imagerd_rt_start not found: {self._start_bin}\n"
                "Check sentry.imagerd_rt_dir in config.json."
            )
        subprocess.Popen(
            [str(self._start_bin)],
            cwd=str(self._dir),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        console_ui.log(f"Launched {self._start_bin}")

    def stop(self):
        """Request graceful shutdown by writing '10' to stop_file."""
        try:
            self._stop_file.write_text("10")
            console_ui.log("Wrote stop_file=10, daemon will stop after current cycle.")
        except Exception as exc:
            console_ui.log(f"Could not write stop_file: {exc}")

    def resume(self):
        """Resume imaging by writing '11' to stop_file."""
        try:
            self._stop_file.write_text("11")
            console_ui.log("Wrote stop_file=11, resuming imaging.")
        except Exception as exc:
            console_ui.log(f"Could not write stop_file: {exc}")

    # ------------------------------------------------------------------
    # Status reads
    # ------------------------------------------------------------------
    def get_seqno(self) -> int:
        """Return current sequence number, or -1 on error."""
        try:
            return int(self._seqno_file.read_text().strip())
        except Exception:
            return -1

    def get_metadata(self) -> dict:
        """Parse and return aux/meta-data.txt as a dict."""
        try:
            return parse_metadata(self._meta_file.read_text())
        except Exception:
            return {}

    def get_latest_image(self) -> "np.ndarray | None":
        """Read aux/image.fits and return as uint16 numpy array, or None."""
        try:
            return np.asarray(frame_archive.read_fits(str(self._image_file)),
                              dtype=np.uint16)
        except Exception:
            return None

    def archive_latest_image(self, output_dir, timestamp=None):
        """Copy aux/image.fits into the archive directory.

        imagerd_rt only ever rewrites its single ``aux/image.fits``; without
        this the configured ``sentry.output_dir`` stayed empty forever and
        there was no archive for the viewer to browse.
        """
        if not output_dir or not self._image_file.exists():
            return None
        stamp = (timestamp or dt.now()).strftime("%Y%m%dT%H%M%S")
        target = os.path.join(output_dir, f"{stamp}.fits")
        tmp = target + ".tmp"
        try:
            os.makedirs(output_dir, exist_ok=True)
            shutil.copy2(str(self._image_file), tmp)
            os.replace(tmp, target)
            return target
        except Exception as exc:
            console_ui.warn(f"SENTRY: could not archive image.fits: {exc}")
            try:
                os.remove(tmp)
            except OSError:
                pass
            return None

    # ------------------------------------------------------------------
    # Schedule generation
    # ------------------------------------------------------------------
    def write_schedule_conf(self, sentry_cfg: dict):
        """Write schedule.conf from the sentry config dict."""
        text = generate_schedule_conf(sentry_cfg)
        tmp = str(self._schedule_conf) + ".tmp"
        with open(tmp, "w") as f:
            f.write(text)
        os.replace(tmp, str(self._schedule_conf))
        console_ui.log(f"Wrote {self._schedule_conf}")


# Kept as module-level names for backwards compatibility; the implementations
# are shared with every other camera driver in frame_archive.
_read_fits_minimal = frame_archive.read_fits_minimal


def frame_to_jpeg_bytes(frame: np.ndarray) -> bytes:
    """Convert a 16-bit (or any) numpy frame to JPEG bytes for MQTT."""
    return frame_archive.to_jpeg_bytes(frame)


# ---------------------------------------------------------------------------
# Console worker
# ---------------------------------------------------------------------------
class SentryWorkerConsole(threading.Thread):
    """Monitors the imagerd_rt daemon and publishes status + frames via MQTT."""

    MAX_CONSECUTIVE_ERRORS = 5

    def __init__(self, cam: SentryCamera, output_dir: str, instance_name: str,
                 status_dir: str, capture_seconds: list,
                 mqtt_publisher=None, mqtt_prefix: str = "every_camera",
                 service=None, node_name: str = "", setup_mode: bool = False):
        super().__init__(daemon=True)
        self.cam = cam
        self.output_dir = output_dir
        self.instance_name = instance_name
        self.status_dir = status_dir
        self.capture_seconds = sorted(capture_seconds)
        self.setup_mode = bool(setup_mode)
        self._service = service
        self._bus = WorkerMqtt("sentry", instance_name, status_dir,
                               mqtt_publisher, mqtt_prefix, service=service,
                               node_name=node_name)
        self._stop_event = threading.Event()
        self._shots = 0          # frames published (not necessarily captured)
        self._errors = 0
        self._last_shot = None
        self._last_frame = None
        self._last_seqno = -1
        self._pending_get_frame = threading.Event()

    def request_stop(self):
        self._stop_event.set()

    # ------------------------------------------------------------------
    # MQTT publish helpers
    # ------------------------------------------------------------------
    def _publish_frame(self, jpeg_bytes: bytes, ts_iso: str,
                       metadata: dict = None, on_demand: bool = False):
        extra = {"metadata": metadata} if metadata else None
        self._bus.publish_frame_jpeg(jpeg_bytes, ts_iso, on_demand=on_demand,
                                     extra=extra)

    def _publish_frame_error(self, status: str, error: str,
                             ts_iso: str = None, on_demand: bool = False):
        self._bus.publish_error(status, error, ts_iso=ts_iso,
                                on_demand=on_demand)

    def _publish_status_note(self, status: str, note: str = ""):
        self._bus.publish_note(status, note)

    # ------------------------------------------------------------------
    # MQTT commands
    # ------------------------------------------------------------------
    def _on_mqtt_command(self, topic: str, payload):
        console_ui.log(f"MQTT cmd: {topic} "
                       f"({len(payload) if payload else 0} bytes)")
        if not self._bus.enabled:
            return
        if topic.endswith("/cmd/get_frame"):
            self._pending_get_frame.set()
            return
        if topic.endswith("/cmd/capture_frame"):
            # sentry camera schedule is autonomous; treat as get_frame
            self._pending_get_frame.set()
            return
        console_ui.log(f"Unknown command: {topic}")

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------
    def run(self):
        self._bus.prepare_status_dir()
        self._bus.subscribe(self._on_mqtt_command)

        # Start daemon if not already running
        if not self.cam.is_running():
            console_ui.log("imagerd_rt not running — starting daemon...")
            try:
                self.cam.start()
                time.sleep(2)  # give it a moment to initialise
            except Exception as exc:
                console_ui.error(f"Could not start imagerd_rt: {exc}")

        if self.setup_mode:
            console_ui.log("Sentry ready for focusing (setup mode) — imagerd_rt "
                           "has no schedule to follow")
            self._save_status(SETUP_STATUS, force=True)
        else:
            console_ui.log("Sentry measurement worker started")
            self._save_status("running", force=True)

        last_fired = (-1, -1)

        while not self._stop_event.is_set():
            # Handle on-demand get_frame request
            if self._pending_get_frame.is_set():
                self._pending_get_frame.clear()
                self._send_latest_frame(on_demand=True)

            now = dt.now()

            # Periodic publish at configured capture_seconds
            fire_key = (now.minute, now.second)
            if now.second in self.capture_seconds and fire_key != last_fired:
                last_fired = fire_key
                seqno = self.cam.get_seqno()
                if seqno != self._last_seqno and seqno > 0:
                    # New frame available
                    self._last_seqno = seqno
                    self._archive_latest(now)
                    self._send_latest_frame(on_demand=False)
                    self._shots += 1
                    self._last_shot = now
                self._save_status(
                    SETUP_STATUS if self.setup_mode else
                    ("running" if self.cam.is_running() else "waiting"),
                    force=True)
            elif now.second not in self.capture_seconds:
                last_fired = (-1, -1)
                self._handle_focus(now)

            self._stop_event.wait(0.1)

        # Graceful stop
        if self.cam.is_running():
            console_ui.log("Stopping imagerd_rt daemon...")
            self.cam.stop()

        self._save_status("stopped", force=True)
        self._bus.shutdown()
        console_ui.log("Sentry measurement worker stopped")

    def _archive_latest(self, now):
        """Keep a dated copy of the daemon's latest FITS in output_dir."""
        if not self.output_dir:
            return
        path = self.cam.archive_latest_image(self.output_dir, now)
        if path:
            console_ui.log(f"SENTRY archived: {os.path.basename(path)}")

    def _handle_focus(self, now):
        """Publish new daemon frames to the LAN live view.

        imagerd_rt owns the schedule and exposure, so there is nothing to
        drive here — the focus tool simply sees each new frame as the daemon
        produces it.
        """
        if self._service is None or not self._service.focus_active():
            return
        seqno = self.cam.get_seqno()
        if seqno <= 0 or seqno == self._last_seqno:
            return
        self._last_seqno = seqno
        frame = self.cam.get_latest_image()
        if frame is not None:
            self._service.publish_frame(frame, now, self.cam.get_metadata())

    def _send_latest_frame(self, on_demand: bool = False):
        """Read aux/image.fits, convert to JPEG, publish via MQTT."""
        frame = self.cam.get_latest_image()
        if frame is None:
            self._publish_frame_error(
                "no_frame", "No image available yet (aux/image.fits missing)",
                ts_iso=dt.now().isoformat(), on_demand=on_demand,
            )
            console_ui.warn("SENTRY: no image.fits available yet")
            return
        try:
            meta = self.cam.get_metadata()
            self._last_frame = frame
            if self._service is not None:
                self._service.publish_frame(frame, dt.now(), meta)
            if not self._bus.enabled:
                return
            jpeg = frame_to_jpeg_bytes(frame)
            ts = meta.get("ExpoTime") or dt.now().isoformat()
            self._publish_frame(jpeg, ts, metadata=meta, on_demand=on_demand)
            console_ui.log(f"SENTRY frame published (seqno={self._last_seqno})")
        except Exception as exc:
            self._errors += 1
            self._publish_frame_error("error", str(exc), ts_iso=dt.now().isoformat(),
                                      on_demand=on_demand)
            console_ui.error(f"SENTRY frame publish: {exc}")

    def _save_status(self, status: str, force: bool = False):
        meta = self.cam.get_metadata()
        seqno = self.cam.get_seqno()
        payload = {
            "instance_name": self.instance_name,
            "camera_type": "sentry",
            "pid": os.getpid(),
            "status": status,
            "output_dir": self.output_dir,
            "shots_taken": self._shots,
            "last_shot": self._last_shot.isoformat() if self._last_shot else None,
            "errors": self._errors,
            "seqno": seqno,
            "capture_seconds": self.capture_seconds,
            "daemon_running": self.cam.is_running(),
            "setup_mode": self.setup_mode,
            "last_update": dt.now().isoformat(),
        }
        # Embed key metadata fields as top-level for monitor display
        for key in ("CCDTemp", "Exposure", "Binning", "CCDGain", "FilterPo",
                    "SiteID", "DeviceID"):
            if key in meta:
                payload[key.lower()] = meta[key]
        try:
            system = get_system_info(self.output_dir or None)
            payload["system"] = system
            console_ui.update(disk_free_mb=system.get("disk_free_mb"))
        except Exception:
            pass
        console_ui.update(status=status, frames=self._shots, errors=self._errors,
                          output_dir=self.output_dir,
                          detail=f"seqno {seqno}" if seqno and seqno > 0 else None)
        console_ui.set_section("camera", [
            ("Daemon:", "running" if payload["daemon_running"] else "not running"),
            ("Sequence number:", str(seqno)),
            ("Sensor temperature:", str(meta.get("CCDTemp", "n/a"))),
            ("Exposure / binning:", f"{meta.get('Exposure', '?')} · "
                                    f"{meta.get('Binning', '?')}"),
            ("Filter:", str(meta.get("FilterPo", "?"))),
        ])
        self._bus.publish_status(payload, force=force)


# ---------------------------------------------------------------------------
# Preview mode
# ---------------------------------------------------------------------------
def run_preview_sentry(cam: SentryCamera, instance_name: str):
    """Continuously read aux/image.fits and overwrite preview_{name}.fits."""
    preview_path = os.path.join(APP_DIR, f"preview_{instance_name}.fits")
    console_ui.log(f"SENTRY preview: reading {cam._image_file} → {preview_path}")
    console_ui.log("Press Ctrl+C to stop.")

    stop = threading.Event()

    def _stop(sig, frame):
        console_ui.log(f"{stop_signal_name(sig)} — stopping preview…")
        stop.set()
    install_stop_handler(_stop)

    import shutil
    frames = 0
    last_seqno = -1
    t0 = dt.now()

    while not stop.is_set():
        seqno = cam.get_seqno()
        if seqno != last_seqno and cam._image_file.exists():
            last_seqno = seqno
            try:
                shutil.copy2(str(cam._image_file), preview_path)
                frames += 1
                if frames % 5 == 0:
                    elapsed = (dt.now() - t0).total_seconds()
                    fps = frames / elapsed if elapsed > 0 else 0
                    meta = cam.get_metadata()
                    console_ui.log(f"Preview: frame {frames}, {fps:.2f} fps, "
                                   f"seqno={seqno}, "
                                   f"temp={meta.get('CCDTemp', '?')}")
            except Exception as exc:
                console_ui.error(f"Preview copy: {exc}")
        time.sleep(0.5)


# ---------------------------------------------------------------------------
# Console entry point
# ---------------------------------------------------------------------------
def run_console_sentry(config_path=None, preview=False, verbose=False,
                       setup_mode=False):
    """Run Sentry (imagerd_rt) camera in console mode."""
    from utils import load_config, get_node_name
    from mqtt_client import create_console_publisher

    cfg = load_config(config_path)
    sentry_cfg = cfg.get("sentry", {})
    mqtt_cfg = cfg.get("mqtt", {})

    node_name = get_node_name(cfg)
    claim = claim_instance_name(sentry_cfg.get("instance_name")
                                or get_instance_name("Sentry", cfg))
    instance_name = claim.name
    imagerd_rt_dir = sentry_cfg.get("imagerd_rt_dir", "/usr/local/imagerd_rt")
    output_dir = sentry_cfg.get("output_dir", "")
    status_dir = cfg.get("status_dir") or str(Path.home() / ".every_camera" / "status")
    capture_seconds = sentry_cfg.get("capture_seconds", SENTRY_CAPTURE_SECONDS)

    dash = console_ui.start_dashboard("sentry", instance_name, verbose=verbose)
    dash.update(status="starting", node_name=node_name, output_dir=output_dir,
                frames=0, errors=0)
    dash.set_section("device", [
        ("imagerd_rt dir:", imagerd_rt_dir),
        ("Publish at:", f"{capture_seconds} s of each minute"),
    ])

    cam = SentryCamera(imagerd_rt_dir)
    mqtt_pub = None
    server = None
    try:
        if not cam.is_available():
            console_ui.error(f"imagerd_rt not found at: {imagerd_rt_dir} — set "
                             f"sentry.imagerd_rt_dir in config.json.")
            return

        if preview:
            run_preview_sentry(cam, instance_name)
            return

        # Write schedule.conf from config if slots are defined. Without slots
        # and without a schedule.conf left by an earlier run, imagerd_rt has no
        # programme to follow — that is setup mode, not a failure.
        if sentry_cfg.get("slots"):
            try:
                cam.write_schedule_conf(sentry_cfg)
            except Exception as exc:
                console_ui.warn(f"Could not write schedule.conf: {exc}")
        elif not os.path.exists(os.path.join(imagerd_rt_dir, "schedule.conf")):
            setup_mode = True
        if setup_mode:
            announce_setup_mode("sentry.slots is empty and no schedule.conf "
                                "exists in " + imagerd_rt_dir)

        if not output_dir:
            console_ui.log("sentry.output_dir not set. Status/MQTT still work; "
                           "FITS archives go wherever imagerd_rt is configured.")

        os.makedirs(status_dir, exist_ok=True)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        mqtt_pub = create_console_publisher(mqtt_cfg, instance_name, "sentry")
        if mqtt_pub:
            dash.update(mqtt=f"{mqtt_cfg.get('host', '?')} — connected")

        # LAN frame server (archive browsing + live view). Never fatal.
        # imagerd_rt owns exposure/schedule, so no remote parameter editing.
        from camera_service import CameraService
        from frame_server import start_frame_server
        service = CameraService("sentry", instance_name, output_dir,
                                supports_params=False, node_name=node_name,
                                setup_mode=setup_mode)
        server = start_frame_server(cfg.get("server", {}), service)
        if server:
            dash.update(server_url=server.url)
            if setup_mode:
                console_ui.log(f"Focus this camera with: python focus_app.py "
                               f"--host {get_local_ip()} --port {server.port}")

        worker = SentryWorkerConsole(
            cam=cam,
            output_dir=output_dir,
            instance_name=instance_name,
            status_dir=status_dir,
            capture_seconds=capture_seconds,
            mqtt_publisher=mqtt_pub,
            mqtt_prefix=mqtt_cfg.get("prefix", "every_camera"),
            service=service,
            node_name=node_name,
            setup_mode=setup_mode,
        )

        def _stop(sig, frame):
            console_ui.log(f"{stop_signal_name(sig)} — stopping…")
            worker.request_stop()
        install_stop_handler(_stop)

        console_ui.log("Starting. Press Ctrl+C to stop.")
        worker.start()
        while worker.is_alive():
            worker.join(timeout=0.5)
    finally:
        if server:
            server.stop()
        if mqtt_pub:
            try:
                mqtt_pub.disconnect_broker()
            except Exception:
                pass
        dash.stop()
        claim.release()
